
name: 'dbt_snow_bridge'
version: '0.0.3'
seed-paths: ["seeds"]
analysis-paths: ["analysis"]
profile: 'default'

model-paths:
  - "models"
  - "ephemeral_models"

# The thread are used in parallel models, i i have 4 models where and 1 thread, 
# then it will run 1 model and then the other, 
# however we need more threads for parrallel computing.
# needed by the dbt internally ot process the commits and commands.
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.




# The thread are used in parallel models, i i have 4 models where and 1 thread, then it will run 1 model and then the other, however we need more threads for parrallel computing.
models:
  # dbt_snow_bridge:
    materialized: table
      # Other matriealisations are View, empehrical, increamental.
      # in sql we only have two materilsed views table and view.
